// <auto-generated />
using BlazorEcommerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorEcommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220618084834_DataSeeding")]
    partial class DataSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorEcommerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Le smartphone est devenu un objet indispensable car il nous permet de faire pleins de choses ! Mais quel système d’exploitation vous convient le mieux, vous prenez beaucoup de photos, vous regardez souvent des vidéos … ?",
                            ImageUrl = "https://www.vandenborre.be/WEB/images/products/300/xiaomi_redmi-9a-32gb-blue-2022_7923260_1.jpg",
                            Price = 208.99m,
                            Title = "SMARTPHONE XIAOMI REDMI 9AS BLUE"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Le smartphone est devenu un objet indispensable car il nous permet de faire pleins de choses ! Mais quel système d’exploitation vous convient le mieux, vous prenez beaucoup de photos, vous regardez souvent des vidéos … ?",
                            ImageUrl = "https://www.vandenborre.be/WEB/images/products/300/xiaomi_xiaomi-redmi-9a-32gb-grey_8187630_1.jpg",
                            Price = 214.99m,
                            Title = "SMARTPHONE XIAOMI REDMI 9A GREY"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Le smartphone est devenu un objet indispensable car il nous permet de faire pleins de choses ! Mais quel système d’exploitation vous convient le mieux, vous prenez beaucoup de photos, vous regardez souvent des vidéos … ?",
                            ImageUrl = "https://www.vandenborre.be/WEB/images/products/300/motorola_moto-e32-slate-grey_7914768_1.jpg",
                            Price = 199.99m,
                            Title = "SMARTPHONE MOTOROLA MOTO E32 SLATE GREY"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
